export { WINDOW_INITIAL_DIMENSIONS } from "./header.consts";
export {
  EXPLORER_WINDOW_HEADER_TEST_ID,
  EXPLORER_WINDOW_CANCEL_BUTTON_TEST_ID,
  EXPLORER_WINDOW_X_CLOSE_BUTTON_TEST_ID,
  EXPLORER_WINDOW_OK_BUTTON_TEST_ID,
  EXPLORER_WINDOW_SUBMIT_BUTTON_TEST_ID,
  EXPLORER_WINDOW_HEADING_TEST_ID,
} from "./test-ids";
